(function(N){
  class ExperienceDirector{
    constructor(){this.root=document.querySelector('#experience');this.audio=document.querySelector('#audio');this.memory=new N.MemoryState();this.cues=new N.CueEngine();this.accessibility=new N.AccessibilityController(this.root);this.governor=new N.PerformanceGovernor(this.root);this.motion=new N.MotionSystem(this.accessibility);this.camera=new N.CameraDirector(this.motion);this.material=new N.MaterialSystem();this.particles=new N.ParticleSystem(this.governor);this.scene=new N.SceneManager(document.querySelector('#webgl'),document.querySelector('#atmosphere'),this.particles,this.governor);this.type=new N.TypographyDirector(this.root);this.lyrics=new N.LyricDirector();this.transition=new N.TransitionEngine(this.root);this.interaction=new N.InteractionManager(this.root,this.memory);this.archive=new N.ArchiveSystem(this.root);this.clock=new N.AudioClock(this.audio);this.clock.setSource('audio/track-01.mp3');this.timeline=this.buildTimeline();this.lastCue='';this.started=false;this.bind();this.update(0,false)}
    buildTimeline(){const tl=gsap.timeline({paused:true,defaults:{ease:'power2.inOut'}});tl.to('#chapter h2',{opacity:1,y:0,duration:3},12).to('#condensation',{opacity:1,duration:7},30).to('.lyric-material',{opacity:1,filter:'blur(0px)',duration:7},34).to('#memory-object',{opacity:1,scale:1,rotation:0,duration:5},45).to('#photograph',{opacity:1,scale:1,rotation:0,duration:7},61).to('#transition-iris',{clipPath:'circle(78% at 50% 50%)',duration:8},70).to('#photograph',{scale:3.7,opacity:.12,duration:8},70).to('#transition-iris',{opacity:0,duration:3},79);return tl}
    bind(){document.querySelector('#enter').onclick=()=>this.enter();document.querySelector('#pause').onclick=()=>this.toggle();document.querySelector('#replay').onclick=()=>this.replay();document.querySelector('#quality').onclick=e=>{e.currentTarget.textContent=`Quality: ${this.cap(this.governor.cycle())}`};document.querySelector('#motion').onclick=e=>{e.currentTarget.textContent=`Motion: ${this.accessibility.toggleMotion()?'Reduced':'Full'}`};document.querySelector('#contrast').onclick=e=>{e.currentTarget.textContent=`Contrast: ${this.accessibility.toggleContrast()?'High':'Standard'}`};this.audio.addEventListener('play',()=>{document.querySelector('#pause span').textContent='Ⅱ';document.querySelector('#pause').ariaLabel='Pause journey'});this.audio.addEventListener('pause',()=>{document.querySelector('#pause span').textContent='▶';document.querySelector('#pause').ariaLabel='Resume journey'});this.audio.addEventListener('error',()=>{document.querySelector('#screen-reader-state').textContent='The historical recording could not be opened.'});this.clock.onFrame((time,paused)=>this.update(time,paused));addEventListener('keydown',e=>{if(e.code==='Space'&&!['BUTTON','INPUT'].includes(document.activeElement.tagName)){e.preventDefault();this.toggle()}if(e.key==='Escape'){this.root.classList.remove('memory-open');this.archive.close()}if(e.key.toLowerCase()==='g')this.archive.open()});this.setupDebug()}
    async enter(){if(this.started)return;this.started=true;this.root.classList.add('entered');try{await this.clock.start()}catch{document.querySelector('#screen-reader-state').textContent='Select pause and resume to begin the recording.'}}
    toggle(){if(!this.started)return this.enter();this.clock.toggle()}
    replay(){this.memory.reset();this.root.classList.remove('slice-complete','memory-open');this.clock.seek(0);this.audio.play()}
    update(time,paused){const now=performance.now();this.governor.sample(now);if(time>=84&&!this.memory.sliceComplete){this.memory.sliceComplete=true;this.audio.pause()}const cue=this.cues.resolve(time);this.memory.phase=cue.phase;this.material.update(time);this.camera.update(time,this.interaction.pointer);this.timeline.time(Math.min(time,this.timeline.duration()),false);this.type.update(cue);this.lyrics.update(cue);this.transition.update(time);this.root.classList.toggle('memory-ready',time>=47&&time<72);document.querySelector('#visual-description').textContent=cue.description;document.querySelector('#debug-output').textContent=time.toFixed(1);if(cue.phase!==this.lastCue){this.lastCue=cue.phase;document.querySelector('#screen-reader-state').textContent=`${cue.label}. ${cue.description}`}
      const profile=this.governor.profile,dpr=[2,1.5,1,1][this.governor.index],phaseIndex=this.cues.cues.indexOf(cue);this.scene.render({time,now,paused,dpr,phase:phaseIndex,material:this.material,camera:this.camera,pointer:this.interaction.pointer,particleCount:this.governor.particles,profile})}
    setupDebug(){const enabled=/[?&]debug=1/.test(location.search)||window.NZ_DEV===true;if(!enabled)return;const panel=document.querySelector('#debug'),range=document.querySelector('#debug-time');panel.hidden=false;range.oninput=()=>{if(!this.started){this.started=true;this.root.classList.add('entered')}this.audio.pause();this.clock.seek(+range.value)};this.clock.onFrame(time=>{if(document.activeElement!==range)range.value=time})}
    cap(value){return value.charAt(0).toUpperCase()+value.slice(1)}
  }
  N.ExperienceDirector=ExperienceDirector;
})(window.NZM);
