(function(N){
  class MaterialSystem{constructor(){this.warmth=0;this.age=.72}update(t){this.warmth=Math.max(0,Math.min(1,(t-12)/48));this.age=.72-.14*this.warmth}}
  class MotionSystem{constructor(access){this.access=access}amount(value){return this.access.reduced?0:value}}
  class CameraDirector{constructor(motion){this.motion=motion;this.x=0;this.y=0;this.push=0}update(t,pointer){this.x=this.motion.amount(pointer.x*.018);this.y=this.motion.amount(pointer.y*.012);this.push=this.motion.amount(Math.max(0,Math.min(1,(t-8)/66))*.16)}}
  class ParticleSystem{constructor(governor){this.governor=governor;this.points=Array.from({length:120},(_,i)=>({x:(Math.sin(i*71.91)*.5+.5),y:(Math.sin(i*117.7)*.5+.5),z:.15+(i%17)/17,s:.35+(i%5)*.24}))}}
  class WebGLRenderer{
    constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'high-performance'});if(!this.gl)throw new Error('WebGL unavailable');this.program=this.makeProgram();this.position=this.gl.getAttribLocation(this.program,'position');this.uniforms={resolution:this.gl.getUniformLocation(this.program,'resolution'),clock:this.gl.getUniformLocation(this.program,'clock'),pointer:this.gl.getUniformLocation(this.program,'pointer'),camera:this.gl.getUniformLocation(this.program,'camera'),warmth:this.gl.getUniformLocation(this.program,'warmth'),phase:this.gl.getUniformLocation(this.program,'phase')};const buffer=this.gl.createBuffer();this.gl.bindBuffer(this.gl.ARRAY_BUFFER,buffer);this.gl.bufferData(this.gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),this.gl.STATIC_DRAW)}
    shader(type,source){const s=this.gl.createShader(type);this.gl.shaderSource(s,source);this.gl.compileShader(s);if(!this.gl.getShaderParameter(s,this.gl.COMPILE_STATUS))throw new Error(this.gl.getShaderInfoLog(s));return s}
    makeProgram(){const vertex=`attribute vec2 position;void main(){gl_Position=vec4(position,0.,1.);}`;const fragment=`precision highp float;uniform vec2 resolution;uniform float clock;uniform vec2 pointer;uniform float camera;uniform float warmth;uniform float phase;float line(float d,float w){return 1.-smoothstep(w,w+1.5/resolution.y,abs(d));}float box(vec2 p,vec2 b){vec2 d=abs(p)-b;return length(max(d,0.))+min(max(d.x,d.y),0.);}void main(){vec2 uv=(gl_FragCoord.xy-.5*resolution)/resolution.y;uv*=1.+camera;uv+=pointer;float vign=1.-smoothstep(.25,.9,length(uv));float paper=fract(sin(dot(gl_FragCoord.xy,vec2(12.9898,78.233)))*43758.5453);vec3 col=mix(vec3(.008,.011,.009),vec3(.028,.032,.026),vign);float breath=sin(clock*.72)*.004*smoothstep(18.,28.,clock);uv.y+=breath;float roof=abs(uv.y-.19+abs(uv.x)*.58);float walls=max(abs(uv.x)-.34,abs(uv.y+.08)-.27);float edge=max(line(roof,.003),line(walls,.002));float door=box(uv-vec2(0.,-.20),vec2(.065,.135));float windowL=box(uv-vec2(-.19,-.05),vec2(.064,.08));float windowR=box(uv-vec2(.19,-.05),vec2(.064,.08));float reveal=smoothstep(7.,24.,clock);float glow=(1.-smoothstep(-.08,.05,min(windowL,windowR)))*smoothstep(25.,48.,clock);col+=edge*reveal*mix(vec3(.20,.17,.12),vec3(.73,.50,.22),warmth);col+=line(door,.002)*reveal*vec3(.58,.42,.23);col+=glow*vec3(.24,.19,.10)*(1.+warmth);float floorLine=line(uv.y+.36,.0015)*smoothstep(10.,18.,clock);col+=floorLine*vec3(.28,.22,.14);col+=(paper-.5)*.025;col*=.7+.3*vign;gl_FragColor=vec4(col,1.);}`;const p=this.gl.createProgram();this.gl.attachShader(p,this.shader(this.gl.VERTEX_SHADER,vertex));this.gl.attachShader(p,this.shader(this.gl.FRAGMENT_SHADER,fragment));this.gl.linkProgram(p);if(!this.gl.getProgramParameter(p,this.gl.LINK_STATUS))throw new Error(this.gl.getProgramInfoLog(p));return p}
    render(state){const gl=this.gl,dpr=state.dpr,w=Math.round(innerWidth*dpr),h=Math.round(innerHeight*dpr);if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;gl.viewport(0,0,w,h)}gl.useProgram(this.program);gl.enableVertexAttribArray(this.position);gl.vertexAttribPointer(this.position,2,gl.FLOAT,false,0,0);gl.uniform2f(this.uniforms.resolution,w,h);gl.uniform1f(this.uniforms.clock,state.time);gl.uniform2f(this.uniforms.pointer,state.camera.x,state.camera.y);gl.uniform1f(this.uniforms.camera,state.camera.push);gl.uniform1f(this.uniforms.warmth,state.material.warmth);gl.uniform1f(this.uniforms.phase,state.phase);gl.drawArrays(gl.TRIANGLES,0,3)}
  }
  class CanvasRenderer{
    constructor(canvas,particles){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.particles=particles}
    render(state,fallback=false){const d=state.dpr,w=innerWidth,h=innerHeight;if(this.canvas.width!==w*d||this.canvas.height!==h*d){this.canvas.width=w*d;this.canvas.height=h*d;this.ctx.setTransform(d,0,0,d,0,0)}const c=this.ctx;c.clearRect(0,0,w,h);if(fallback){const s=Math.min(w/820,h/780),cx=w*.54,cy=h*.56;c.save();c.translate(cx,cy);c.scale(s,s);c.strokeStyle=`rgba(201,159,88,${Math.min(.7,state.time/18)})`;c.lineWidth=1.2;c.beginPath();c.moveTo(-260,180);c.lineTo(-260,-120);c.lineTo(0,-310);c.lineTo(260,-120);c.lineTo(260,180);c.closePath();c.stroke();c.strokeRect(-50,30,100,150);c.restore()}const count=Math.min(this.particles.points.length,state.particleCount);for(let i=0;i<count;i++){const p=this.particles.points[i],influence=1/(.25+Math.hypot(p.x-state.pointer.nx,p.y-state.pointer.ny));const x=(p.x*w+Math.sin(state.now*.0002+i)*10*p.z+state.pointer.x*influence*5)%w;const y=(p.y*h-state.time*(.4+p.z*.8)+h)%h;c.fillStyle=`rgba(220,195,145,${.025+p.z*.08})`;c.fillRect(x,y,p.s,p.s)}if(state.time>43&&state.time<68){const q=Math.min(1,(state.time-43)/8);c.save();c.translate(w*.62,h*.62);c.strokeStyle=`rgba(215,171,96,${q*.18})`;for(let r=0;r<4;r++){c.beginPath();c.arc(0,0,35+r*18+Math.sin(state.now*.001+r)*4,0,Math.PI*2);c.stroke()}c.restore()}}
  }
  class SceneManager{
    constructor(webglCanvas,overlayCanvas,particles,governor){this.governor=governor;try{this.primary=new WebGLRenderer(webglCanvas);this.webgl=true}catch{this.webgl=false;governor.index=3;governor.apply()}this.overlay=new CanvasRenderer(overlayCanvas,particles)}
    render(state){if(this.primary)this.primary.render(state);this.overlay.render(state,!this.webgl)}
  }
  class TypographyDirector{constructor(root){this.root=root;this.last=''}update(cue){if(cue.phase===this.last)return;this.last=cue.phase;this.root.dataset.phase=cue.phase;document.querySelector('.narrative-label').textContent=cue.label;document.querySelector('.narrative-line').textContent=cue.line;gsap.fromTo('#narrative',{opacity:0,y:10},{opacity:1,y:0,duration:1.15,ease:'power2.out',overwrite:true})}}
  class LyricDirector{constructor(){this.stable=document.querySelector('#stable-lyric')}update(cue){this.stable.textContent=cue.lyric||'The first lyric has not yet surfaced.'}}
  class TransitionEngine{constructor(root){this.root=root}update(time){this.root.classList.toggle('slice-complete',time>=82)}}
  N.MaterialSystem=MaterialSystem;N.MotionSystem=MotionSystem;N.CameraDirector=CameraDirector;N.ParticleSystem=ParticleSystem;N.SceneManager=SceneManager;N.TypographyDirector=TypographyDirector;N.LyricDirector=LyricDirector;N.TransitionEngine=TransitionEngine;
})(window.NZM);
