import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import TRANSCENDENCE_HTML from './TRANSCENDENCE.html?raw';
import versions from './TRANSCENDENCE.versions.json';
import { MARKERS, findUnfilledMarkers } from '../experiences/transcendence/markers.js';
import { assertTemplatePrebuilt } from '../utils/transcendence.js';

const packageJson = JSON.parse(readFileSync(new URL('../../../package.json', import.meta.url), 'utf8'));

/**
 * TRANSCENDENCE.html is generated by scripts/build-transcendence-template.mjs and
 * committed, so a fresh clone can run `npx vitest` and `vite dev` with no generate
 * step. The cost of committing a generated artefact is that it can go stale
 * silently; these tests are what makes it fail loudly instead.
 */
describe('the prebuilt Transcendence template', () => {
  it('has Three.js and GSAP inlined', () => {
    expect(TRANSCENDENCE_HTML).not.toContain('/* THREE_RUNTIME */');
    expect(TRANSCENDENCE_HTML).not.toContain('/* GSAP_RUNTIME */');
    expect(TRANSCENDENCE_HTML).toContain('window.THREE=Object.assign');
    expect(() => assertTemplatePrebuilt(TRANSCENDENCE_HTML)).not.toThrow();
  });

  it('was built from the versions this project actually depends on', () => {
    // A `npm install` that bumps three or gsap without regenerating the template
    // would ship a renderer that does not match the lockfile. This is the signal.
    expect(versions.three).toBe(packageJson.dependencies.three);
    expect(versions.gsap).toBe(packageJson.dependencies.gsap);
  });

  it('still declares every marker the builders fill', () => {
    // A marker removed from experience.html but still filled by a builder is a
    // silent no-op; one added but not filled ships `/* TX_TITLE */` to a collector.
    const prebuilt = new Set(['three', 'gsap']);
    for (const { token, key } of MARKERS) {
      if (prebuilt.has(key)) continue;
      expect(TRANSCENDENCE_HTML.includes(token), `${token} is missing from the template`).toBe(true);
    }
  });

  it('reports its remaining markers as unfilled until a builder fills them', () => {
    const remaining = findUnfilledMarkers(TRANSCENDENCE_HTML);
    expect(remaining).toContain('TX_TITLE');
    expect(remaining).toContain('ANALYSIS_PAYLOAD');
    expect(remaining).toContain('SEQUENCE_PAYLOAD');
    expect(remaining).toContain('CONFIG_PAYLOAD');
  });

  it('cannot reach the network', () => {
    const csp = TRANSCENDENCE_HTML.match(
      /<meta[^>]+http-equiv=["']Content-Security-Policy["'][^>]*content=(["'])([\s\S]*?)\1/i,
    );
    expect(csp?.[2]).toMatch(/connect-src\s+'none'/);
    // No element loads anything remote. The inlined Three.js and GSAP do contain
    // URLs in comments and licence notices — a paper citation in a shader, a link
    // to the GSAP licence — and those are inert text, which is why the check is on
    // fetchable positions rather than on the string "https://".
    const loaders = [...TRANSCENDENCE_HTML.matchAll(
      /\b(?:src|href|poster|srcset|action)\s*=\s*["']?(https?:\/\/[^\s"'>]+)/gi,
    )].map((match) => match[1]).filter((url) => !url.startsWith('http://www.w3.org/'));
    expect(loaders).toEqual([]);
  });

  it('carries no reference to the recording it was extracted from', () => {
    // The runtime is shared with every Studio-authored object now, so nothing in
    // it may be about the 1902 disc the reference edition ships.
    for (const term of ['Home, Sweet Home', 'Macdonough', 'D’Almaine', 'track-01.mp3']) {
      expect(TRANSCENDENCE_HTML, `template still mentions ${term}`).not.toContain(term);
    }
  });
});
