[build]
  command = "npm run build"
  publish = ".netlify/static"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/_app/immutable/*"
  [headers.values]
    cache-control = "public, immutable, max-age=31536000"
