(function(N){
  class ExperienceDirector{
    constructor(){this.root=document.querySelector('#experience');this.audio=document.querySelector('#audio');this.memory=new N.MemoryState();this.cues=new N.CueEngine();this.accessibility=new N.AccessibilityController(this.root);this.governor=new N.PerformanceGovernor(this.root);this.motion=new N.MotionSystem(this.accessibility);this.camera=new N.CameraDirector(this.motion);this.material=new N.MaterialSystem();this.particles=new N.ParticleSystem(this.governor);this.scene=new N.SceneManager(document.querySelector('#world'),document.querySelector('#film'),this.particles,this.governor,this.accessibility);this.type=new N.TypographyDirector(this.root);this.lyrics=new N.LyricDirector();this.transition=new N.TransitionEngine(this.root);this.interaction=new N.InteractionManager(this.root,this.memory);this.archive=new N.ArchiveSystem(this.root);this.clock=new N.AudioClock(this.audio);this.spatial=new N.SpatialAudioSystem(this.audio);this.clock.setSource('audio/track-01.mp3');this.lastCue='';this.started=false;this.bind();this.update(0,false)}
    bind(){document.querySelector('#enter').onclick=()=>this.enter();document.querySelector('#pause').onclick=()=>this.toggle();document.querySelector('#replay').onclick=()=>this.replay();document.querySelector('#quality').onclick=e=>{e.currentTarget.textContent=`Quality · ${this.cap(this.governor.cycle())}`};document.querySelector('#motion').onclick=e=>{e.currentTarget.textContent=`Motion · ${this.accessibility.toggleMotion()?'Reduced':'Full'}`};document.querySelector('#contrast').onclick=e=>{e.currentTarget.textContent=`Contrast · ${this.accessibility.toggleContrast()?'High':'Standard'}`};this.audio.addEventListener('play',()=>{document.querySelector('#pause').textContent='Ⅱ';document.querySelector('#pause').ariaLabel='Pause journey'});this.audio.addEventListener('pause',()=>{document.querySelector('#pause').textContent='▶';document.querySelector('#pause').ariaLabel='Resume journey'});this.audio.addEventListener('error',()=>document.querySelector('#sr-state').textContent='The historical recording could not be opened.');this.clock.onFrame((time,paused)=>this.update(time,paused));addEventListener('keydown',e=>{if(e.code==='Space'&&!['BUTTON','INPUT'].includes(document.activeElement.tagName)){e.preventDefault();this.toggle()}if(e.key==='Escape')this.archive.close();if(e.key.toLowerCase()==='g')this.archive.open()});this.setupDebug()}
    async enter(){if(this.started)return;this.started=true;this.root.classList.add('entered');try{await this.spatial.start();await this.clock.start()}catch(error){console.warn(error);document.querySelector('#sr-state').textContent='Select pause and resume to begin the recording.'}}
    toggle(){if(!this.started)return this.enter();this.clock.toggle()}
    replay(){this.memory.reset();this.root.classList.remove('slice-complete','memory-open');this.clock.seek(0);this.audio.play()}
    update(time,paused){const now=performance.now();this.governor.sample(now);if(time>=84&&!this.memory.sliceComplete){this.memory.sliceComplete=true;this.audio.pause()}const cue=this.cues.resolve(time);this.memory.phase=cue.phase;this.material.update(time);this.camera.update(time,this.interaction.pointer);this.type.update(cue);this.lyrics.update(cue);this.transition.update(time);this.spatial.update(time,cue);this.root.classList.toggle('key-ready',time>=62&&time<78);document.querySelector('#scene-description').textContent=cue.description;if(cue.phase!==this.lastCue){this.lastCue=cue.phase;document.querySelector('#sr-state').textContent=cue.description}this.scene.render({time,now,paused,material:this.material,camera:this.camera,pointer:this.interaction.pointer,particleCount:this.governor.particles,profile:this.governor.profile});this.debugState(time,cue)}
    setupDebug(){const enabled=/[?&]debug=1/.test(location.search)||window.NZ_DEV===true;if(!enabled)return;const panel=document.querySelector('#debug'),range=document.querySelector('#debug-time'),jumps={object:0,entry:8,fall:14,reconstruction:26,breath:40,inscription:52,key:64,photograph:73,passage:79};panel.hidden=false;const holder=panel.querySelector('.debug-jumps');for(const[name,time]of Object.entries(jumps)){const button=document.createElement('button');button.textContent=name;button.onclick=()=>{this.started=true;this.root.classList.add('entered');this.clock.preview(time)};holder.append(button)}range.oninput=()=>{this.started=true;this.root.classList.add('entered');this.clock.preview(+range.value)};this.clock.onFrame(time=>{if(document.activeElement!==range)range.value=time});document.querySelector('#debug-capture').onclick=()=>{const snapshot=this.captureState();navigator.clipboard?.writeText(JSON.stringify(snapshot,null,2))}}
    debugState(time,cue){const out=document.querySelector('#debug-output');if(out)out.textContent=JSON.stringify(this.captureState(time,cue),(key,value)=>key==='_gsap'?undefined:value)}
    captureState(time=this.clock.time,cue=this.cues.resolve(time)){const c=this.camera.state;return{time:+time.toFixed(2),cue:cue.phase,camera:{x:c.x,y:c.y,z:c.z,tx:c.tx,ty:c.ty,tz:c.tz,fov:c.fov},quality:this.governor.profile,frameMs:+(this.governor.samples.at(-1)||0).toFixed(1),renderer:this.scene.stats,emitters:this.spatial.emitters||0,world:this.memory.phase,memories:[...this.memory.discovered]}}
    cap(value){return value.charAt(0).toUpperCase()+value.slice(1)}
  }
  N.ExperienceDirector=ExperienceDirector;
})(window.NZM);
