(function(N){
  const T=window.THREE;
  const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
  const smooth=(a,b,v)=>{const x=clamp((v-a)/(b-a));return x*x*(3-2*x)};
  class MaterialSystem{
    constructor(){this.recovery=0;this.warmth=0;this.condensation=0;this.portal=0}
    update(time){this.recovery=smooth(24,38,time);this.warmth=smooth(38,62,time);this.condensation=smooth(49,57,time);this.portal=smooth(72,83,time)}
  }
  class MotionSystem{constructor(access){this.access=access}amount(v){return this.access.reduced?0:v}}
  class CameraDirector{
    constructor(motion){this.motion=motion;this.state={x:0,y:1.55,z:4.2,tx:0,ty:1.3,tz:-8,fov:44};this.pointer={x:0,y:0};this.timeline=gsap.timeline({paused:true,defaults:{ease:'power2.inOut'}}).to(this.state,{z:2.5,y:1.5,duration:12},0).to(this.state,{z:-2.2,ty:1.1,tz:-11,duration:12,ease:'power3.in'},12).to(this.state,{x:-.8,z:-.2,tx:0,ty:1.6,tz:-10,duration:14},24).to(this.state,{x:.3,z:-1.3,tx:.3,ty:1.75,tz:-10.6,duration:12},38).to(this.state,{x:1.05,y:1.4,z:-3.2,tx:1.25,ty:1.05,tz:-9.2,duration:12},50).to(this.state,{x:.5,y:1.45,z:-5.1,tx:-1.5,ty:1.65,tz:-9.55,duration:10},62).to(this.state,{x:-1.4,y:1.55,z:-8.85,tx:-1.45,ty:1.55,tz:-13,duration:12,ease:'power2.in'},72)}
    update(time,pointer){this.timeline.time(Math.min(time,this.timeline.duration()),false);this.pointer.x+=(pointer.x-this.pointer.x)*.035;this.pointer.y+=(pointer.y-this.pointer.y)*.035}
    apply(camera){const sway=this.motion.amount(Math.sin(performance.now()*.0007)*.012),portraitPull=camera.aspect<.72?3.8:0;camera.position.set(this.state.x+this.pointer.x*.075,this.state.y-this.pointer.y*.045+sway,this.state.z+portraitPull);camera.fov=this.state.fov;camera.updateProjectionMatrix();camera.lookAt(this.state.tx+this.pointer.x*.13,this.state.ty-this.pointer.y*.08,this.state.tz)}
  }
  class ParticleSystem{constructor(governor){this.governor=governor}}
  class TextureAtlas{
    constructor(url,columns=3,rows=3){this.columns=columns;this.rows=rows;this.tiles=[];this.source=new T.TextureLoader().load(url,loaded=>{for(const tile of this.tiles){tile.image=loaded.image;tile.needsUpdate=true}});this.source.colorSpace=T.SRGBColorSpace;this.source.wrapS=this.source.wrapT=T.RepeatWrapping;this.source.anisotropy=4}
    tile(index){const texture=new T.Texture(),w=1/this.columns,h=1/this.rows;texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.anisotropy=4;texture.repeat.set(w,h);texture.offset.set((index%this.columns)*w,1-Math.floor(index/this.columns)*h-h);texture.colorSpace=T.SRGBColorSpace;this.tiles.push(texture);if(this.source.image){texture.image=this.source.image;texture.needsUpdate=true}return texture}
  }
  class WorldRenderer{
    constructor(canvas,governor,access){this.canvas=canvas;this.governor=governor;this.access=access;this.renderer=new T.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.24;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFShadowMap;this.scene=new T.Scene();this.scene.background=new T.Color(0x020403);this.scene.fog=new T.FogExp2(0x07100d,.026);this.camera=new T.PerspectiveCamera(44,innerWidth/innerHeight,.04,90);this.camera.position.set(0,1.55,4.2);this.stats={drawCalls:0,triangles:0,textures:0,lights:0};this.objects={};this.loaded=false;this.build()}
    mat(color,rough=.8,metal=0,map=null){return new T.MeshStandardMaterial({color,roughness:rough,metalness:metal,map,emissive:color,emissiveIntensity:metal>.4?.045:.12})}
    mesh(geometry,material,parent=this.scene,position=[0,0,0],rotation=[0,0,0]){const mesh=new T.Mesh(geometry,material);mesh.position.set(...position);mesh.rotation.set(...rotation);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh}
    build(){const resource=path=>window.NZ_RESOURCE_URLS?.[path]||path,atlasUrl=resource('assets/images/world-atlas.png'),ephemeraUrl=resource('assets/images/memory-ephemera-atlas.png'),panoramaUrl=resource('assets/images/exterior-panorama.png');this.atlas=new TextureAtlas(atlasUrl);this.ephemera=new TextureAtlas(ephemeraUrl,4,2);const panorama=new T.TextureLoader().load(panoramaUrl);panorama.colorSpace=T.SRGBColorSpace;const plaster=this.mat(0x75827a,.86,0,this.atlas.tile(0)),wood=this.mat(0x77513a,.78,0,this.atlas.tile(1)),wallpaper=this.mat(0x77775e,.86,0,this.atlas.tile(2)),brass=this.mat(0xd0a359,.3,.72,this.atlas.tile(3)),glass=new T.MeshPhysicalMaterial({color:0xadc7c2,roughness:.3,transmission:.28,transparent:true,opacity:.72,map:this.atlas.tile(4),depthWrite:false,emissive:0x182421,emissiveIntensity:.24}),paper=this.mat(0xd8c9a8,.95,0,this.atlas.tile(5)),photo=this.mat(0xb59c70,.8,0,this.ephemera.tile(0)),cloth=this.mat(0x2b3029,1,0,this.atlas.tile(8));this.materials={plaster,wood,wallpaper,brass,glass,paper,photo,cloth};
      this.ambient=new T.HemisphereLight(0x9aaeb0,0x21170e,.42);this.scene.add(this.ambient);this.moon=new T.DirectionalLight(0xa8bdd0,2.25);this.moon.position.set(-6,10,4);this.moon.castShadow=true;this.moon.shadow.mapSize.set(1024,1024);this.scene.add(this.moon);this.frontFill=new T.DirectionalLight(0x91a7a3,1.15);this.frontFill.position.set(2,4,7);this.frontFill.target.position.set(0,2,-10);this.scene.add(this.frontFill,this.frontFill.target);this.memoryLight=new T.PointLight(0xd59a48,0,14,1.8);this.memoryLight.position.set(.5,2,-8);this.scene.add(this.memoryLight);this.objectLight=new T.PointLight(0xd8b77d,4.2,13,1.7);this.objectLight.position.set(-2.8,4.8,1.5);this.scene.add(this.objectLight);this.stats.lights=5;
      this.objectGroup=new T.Group();this.scene.add(this.objectGroup);const caseMat=this.mat(0x5b5c4d,.68,.18,cloth.map);caseMat.emissive.setHex(0x2a2416);caseMat.emissiveIntensity=.9;this.caseL=this.mesh(new T.BoxGeometry(2.8,3.8,.24),caseMat,this.objectGroup,[-1.42,0,-3.4],[0,.02,0]);this.caseR=this.mesh(new T.BoxGeometry(2.8,3.8,.24),caseMat,this.objectGroup,[1.42,0,-3.4],[0,-.02,0]);const sealTex=this.makeLabelTexture();const sealMat=new T.MeshStandardMaterial({map:sealTex,transparent:true,roughness:.72,emissive:0x35200a,emissiveIntensity:.7});this.seal=this.mesh(new T.PlaneGeometry(2.25,1.28),sealMat,this.objectGroup,[0,0,-3.265]);this.objectGroup.position.y=1.45;this.objectGroup.rotation.x=-.08;
      this.world=new T.Group();this.world.visible=false;this.scene.add(this.world);this.backdrop=this.mesh(new T.PlaneGeometry(62,26),new T.MeshBasicMaterial({map:panorama,fog:false,toneMapped:false,color:0xaab5a9}),this.world,[0,10,-38]);this.terrain=this.mesh(new T.PlaneGeometry(60,60,20,20),this.mat(0x182019,1),this.world,[0,0,-10],[-Math.PI/2,0,0]);
      this.house=new T.Group();this.world.add(this.house);this.house.position.z=-10;this.mesh(new T.BoxGeometry(3,4.7,.38),plaster,this.house,[-2.25,2.35,0]);this.mesh(new T.BoxGeometry(3,4.7,.38),plaster,this.house,[2.25,2.35,0]);this.mesh(new T.BoxGeometry(1.5,1.85,.38),plaster,this.house,[0,3.78,0]);const roof=this.mesh(new T.ConeGeometry(5.3,2.5,4),this.mat(0x4a3424,.9),this.house,[0,5.35,0],[0,Math.PI/4,0]);roof.scale.z=.62;const sideL=this.mesh(new T.BoxGeometry(.35,4.7,8),plaster,this.house,[-3.58,2.35,-3.8]);const sideR=this.mesh(new T.BoxGeometry(.35,4.7,8),plaster,this.house,[3.58,2.35,-3.8]);
      this.door=this.mesh(new T.BoxGeometry(1.45,2.75,.18),wood,this.house,[0,1.38,.32]);this.door.geometry.translate(-.7,0,0);this.door.position.x=.7;this.doorHinge=new T.Group();this.house.add(this.doorHinge);this.doorHinge.position.set(-.7,1.38,.43);this.house.remove(this.door);this.door.position.set(.7,0,0);this.doorHinge.add(this.door);
      const windowGeo=new T.BoxGeometry(1.25,1.55,.14);this.windowL=this.mesh(windowGeo,glass,this.house,[-2.25,2.65,.31]);this.windowR=this.mesh(windowGeo,glass,this.house,[2.25,2.65,.31]);for(const x of [-2.25,2.25]){this.mesh(new T.BoxGeometry(1.55,.1,.23),wood,this.house,[x,1.85,.38]);this.mesh(new T.BoxGeometry(.1,1.8,.23),wood,this.house,[x,2.65,.38])}
      this.porch=new T.Group();this.house.add(this.porch);this.mesh(new T.BoxGeometry(6.4,.22,2.7),wood,this.porch,[0,.12,1.25]);for(const x of [-2.7,2.7])this.mesh(new T.CylinderGeometry(.11,.14,3.6,10),wood,this.porch,[x,1.9,1.8]);this.mesh(new T.BoxGeometry(6.5,.18,2.5),wood,this.porch,[0,3.75,1.35]);for(let i=0;i<4;i++)this.mesh(new T.BoxGeometry(3.2,.22,.52),wood,this.porch,[0,-.1-i*.17,2.05+i*.38]);
      this.hall=new T.Group();this.house.add(this.hall);this.mesh(new T.BoxGeometry(4.6,.18,12),wood,this.hall,[0,.02,-5.8]);this.mesh(new T.BoxGeometry(.18,4.2,12),wallpaper,this.hall,[-2.3,2.1,-5.8]);this.mesh(new T.BoxGeometry(.18,4.2,12),wallpaper,this.hall,[2.3,2.1,-5.8]);this.mesh(new T.BoxGeometry(4.6,.18,12),plaster,this.hall,[0,4.2,-5.8]);
      this.table=this.mesh(new T.BoxGeometry(1.5,.12,.72),wood,this.hall,[0,1.05,-1.7]);for(const x of [-.57,.57])for(const z of [-1.45,-1.95])this.mesh(new T.BoxGeometry(.08,1,.08),wood,this.hall,[x,.52,z]);
      this.key=new T.Group();this.hall.add(this.key);this.key.position.set(-.12,1.18,-1.65);this.key.visible=false;this.mesh(new T.TorusGeometry(.18,.045,10,28),brass,this.key);this.mesh(new T.BoxGeometry(.48,.075,.075),brass,this.key,[.35,0,0]);this.mesh(new T.BoxGeometry(.075,.2,.075),brass,this.key,[.56,-.08,0]);this.key.rotation.set(-Math.PI/2,0,.18);
      this.photoFrame=new T.Group();this.house.add(this.photoFrame);this.photoFrame.position.set(-1.47,1.75,.42);this.photoFrame.visible=false;this.mesh(new T.BoxGeometry(1.62,1.95,.1),wood,this.photoFrame);this.photoPlane=this.mesh(new T.PlaneGeometry(1.35,1.67),photo,this.photoFrame,[0,0,.065]);this.portalSurface=this.mesh(new T.PlaneGeometry(1.3,1.62),new T.MeshBasicMaterial({color:0x111611,transparent:true,opacity:0}),this.photoFrame,[0,0,.09]);
      for(let i=1;i<4;i++){const memory=this.mesh(new T.PlaneGeometry(.72,.86),new T.MeshStandardMaterial({map:this.ephemera.tile(i),roughness:.86}),this.hall,[i%2? -2.18:2.18,1.7,-2.7-i*1.75],[0,i%2?Math.PI/2:-Math.PI/2,0]);memory.castShadow=false}
      this.lyricPlane=this.mesh(new T.PlaneGeometry(1.12,1.38),new T.MeshBasicMaterial({map:this.makeLyricTexture(),transparent:true,opacity:0,depthWrite:false}),this.house,[-2.25,2.65,.42]);
      this.tree=new T.Group();this.world.add(this.tree);this.tree.position.set(-7,0,-6);const bark=this.mat(0x181810,1);this.mesh(new T.CylinderGeometry(.36,.55,7,9),bark,this.tree,[0,3.5,0],[0,0,.08]);for(let i=0;i<14;i++){const branch=this.mesh(new T.CylinderGeometry(.035,.13,2.8+i%3*.4,7),bark,this.tree,[Math.sin(i)*.8,5+(i%4)*.45,Math.cos(i)*.5]);branch.rotation.set(Math.sin(i*2)*.7,0,Math.cos(i)*1.1)}
      const dustGeo=new T.BufferGeometry(),count=220,pos=new Float32Array(count*3);for(let i=0;i<count;i++){pos[i*3]=(Math.random()-.5)*14;pos[i*3+1]=Math.random()*7;pos[i*3+2]=-5-Math.random()*13}dustGeo.setAttribute('position',new T.BufferAttribute(pos,3));this.dust=new T.Points(dustGeo,new T.PointsMaterial({color:0xd8c18e,size:.025,transparent:true,opacity:.45,depthWrite:false}));this.world.add(this.dust);
      this.beam=this.mesh(new T.ConeGeometry(1.8,8,16,1,true),new T.MeshBasicMaterial({color:0xa7c2c0,transparent:true,opacity:.035,side:T.DoubleSide,depthWrite:false}),this.world,[-3.5,4,-5],[0,0,-.5]);this.world.traverse(o=>{if(o.material&&o!==this.dust)o.material.transparent=true;o.userData.baseY=o.position.y});this.loaded=true}
    makeLabelTexture(){const c=document.createElement('canvas');c.width=1024;c.height=600;const x=c.getContext('2d');x.fillStyle='#171a15';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#927548';x.lineWidth=4;x.strokeRect(40,40,944,520);x.fillStyle='#c8b282';x.textAlign='center';x.font='24px Georgia';x.letterSpacing='8px';x.fillText('THE HOUSE THAT REMEMBERED US',512,245);x.font='16px monospace';x.fillText('NOIZES OBJECT 001 / 001',512,315);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
    makeLyricTexture(){const c=document.createElement('canvas');c.width=1024;c.height=1024;const x=c.getContext('2d');x.clearRect(0,0,1024,1024);x.fillStyle='rgba(224,235,230,.86)';x.textAlign='center';x.font='italic 58px Georgia';x.shadowColor='rgba(210,235,228,.7)';x.shadowBlur=18;x.fillText("'Mid pleasures and palaces",512,470);x.fillText('though we may roam',512,545);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
    resize(){const dpr=[2,1.5,1,1][this.governor.index],w=innerWidth,h=innerHeight;this.renderer.setPixelRatio(Math.min(devicePixelRatio,dpr));this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
    render(state){this.resize();const t=state.time,m=state.material;this.world.visible=t>=11;this.objectGroup.visible=t<25;const unfold=smooth(7,18,t);this.caseL.rotation.y=-unfold*1.42;this.caseR.rotation.y=unfold*1.42;this.caseL.position.x=-1.42-unfold*.8;this.caseR.position.x=1.42+unfold*.8;this.seal.material.opacity=1-smooth(6,12,t);this.objectGroup.scale.setScalar(1+smooth(10,24,t)*2.5);
      this.house.traverse(o=>{if(o.material&&o.material!==this.materials.glass&&!Array.isArray(o.material))o.material.opacity=.32+.68*m.recovery});this.terrain.material.opacity=.32+.68*m.recovery;this.objectLight.intensity=5.2*(1-smooth(8,23,t));this.memoryLight.intensity=3.1*m.warmth;this.ambient.intensity=.44+.4*m.warmth;this.frontFill.intensity=.85+1.15*m.recovery;this.moon.intensity=2.1+smooth(24,34,t)*1.6;
      const breath=smooth(38,42,t)*(1-smooth(49,52,t))*Math.sin((t-38)*Math.PI*.72);this.windowL.position.z=.31+breath*.035;this.windowR.position.z=.31+breath*.035;this.porch.rotation.x=breath*.004;this.dust.rotation.y+=state.paused?0:.00012;this.dust.material.opacity=.2+.35*m.recovery;this.lyricPlane.material.opacity=m.condensation*(1-.32*smooth(62,70,t));this.lyricPlane.position.y=2.65-smooth(58,70,t)*.04;
      this.key.visible=t>=61;const keyReveal=smooth(61,68,t);this.key.scale.setScalar(keyReveal);this.key.rotation.z=.18+Math.sin(state.now*.001)*.025*(1-state.paused);this.key.position.y=1.18+Math.sin(state.now*.0014)*.025*(1-state.paused);this.photoFrame.visible=t>=70;const p=smooth(70,77,t);this.photoFrame.scale.setScalar(.72+.28*p);this.photoPlane.material.opacity=.1+.9*p;this.portalSurface.material.opacity=smooth(76,82,t)*.88;this.portalSurface.material.color.setHSL(.12,.18,.08+.13*smooth(76,82,t));this.doorHinge.rotation.y=-smooth(59,68,t)*.82-smooth(71,82,t)*.33;
      this.scene.fog.density=.026-.014*smooth(72,84,t);state.camera.apply(this.camera);this.renderer.render(this.scene,this.camera);const info=this.renderer.info.render;this.stats={drawCalls:info.calls,triangles:info.triangles,textures:this.renderer.info.memory.textures,lights:5};this.projectKey()}
    projectKey(){if(!this.key.visible)return;const p=new T.Vector3();this.key.getWorldPosition(p);p.project(this.camera);const el=document.querySelector('#key-presence');el.style.left=`${(p.x*.5+.5)*innerWidth}px`;el.style.top=`${(-p.y*.5+.5)*innerHeight}px`}
    dispose(){this.renderer.dispose()}
  }
  class CanvasFilm{
    constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d')}
    render(state){const d=Math.min(devicePixelRatio,1.25),w=innerWidth,h=innerHeight;if(this.canvas.width!==w*d||this.canvas.height!==h*d){this.canvas.width=w*d;this.canvas.height=h*d;this.ctx.setTransform(d,0,0,d,0,0)}const c=this.ctx;c.clearRect(0,0,w,h);for(let i=0;i<180;i++){const x=(Math.sin(i*88.1+state.now*.0001)*.5+.5)*w,y=(Math.sin(i*37.7-state.now*.00008)*.5+.5)*h;c.fillStyle=`rgba(236,221,185,${.006+(i%5)*.002})`;c.fillRect(x,y,1,1)}if(state.material.condensation>.2){const g=c.createRadialGradient(w*.36,h*.43,0,w*.36,h*.43,w*.18);g.addColorStop(0,`rgba(190,215,208,${state.material.condensation*.025})`);g.addColorStop(1,'transparent');c.fillStyle=g;c.fillRect(0,0,w,h)}}
  }
  class SceneManager{
    constructor(canvas,film,particles,governor,access){this.governor=governor;try{this.primary=new WorldRenderer(canvas,governor,access);this.webgl=true}catch(error){console.warn(error);this.webgl=false;governor.index=3;governor.apply()}this.film=new CanvasFilm(film);this.stats=this.primary?.stats||{drawCalls:0,triangles:0,textures:0,lights:0}}
    render(state){if(this.primary){this.primary.render(state);this.stats=this.primary.stats}this.film.render(state)}
  }
  class TypographyDirector{constructor(root){this.root=root;this.last=''}update(cue){if(cue.phase===this.last)return;this.last=cue.phase;this.root.dataset.world=cue.phase}}
  class LyricDirector{constructor(){this.stable=document.querySelector('#stable-lyric')}update(cue){this.stable.textContent=cue.lyric||'The lyric has not yet formed on the glass.'}}
  class TransitionEngine{constructor(root){this.root=root}update(time){this.root.classList.toggle('slice-complete',time>=82)}}
  N.MaterialSystem=MaterialSystem;N.MotionSystem=MotionSystem;N.CameraDirector=CameraDirector;N.ParticleSystem=ParticleSystem;N.SceneManager=SceneManager;N.TypographyDirector=TypographyDirector;N.LyricDirector=LyricDirector;N.TransitionEngine=TransitionEngine;
})(window.NZM);
