import nodeCrypto from 'node:crypto';

// Currencies the Spec Music Paystack (KE) account can charge today. Widen only
// after Paystack confirms card-currency support (T4b ticket in TODOS.md).
export const SUPPORTED_CURRENCIES = ['KES'];

const PAYSTACK_API = 'https://api.paystack.co';

// Transaction reference, generated by us at init and passed to Paystack.
// Doubles as the idempotency key on acquisitions.payment_reference.
export function makeReference() {
  return `nz_${nodeCrypto.randomUUID()}`;
}

// Paystack charges in subunits (KES cents). Always computed server-side from
// the release's DB price — never trusted from the client.
export function toSubunits(price, currency) {
  if (!SUPPORTED_CURRENCIES.includes(currency)) {
    throw new Error(`Unsupported currency: ${currency}`);
  }
  const n = Number(price);
  if (!Number.isFinite(n) || n < 0) {
    throw new Error(`Invalid price: ${price}`);
  }
  return Math.round(n * 100);
}

// Paystack signs webhook bodies with HMAC-SHA512 of the raw bytes using the
// secret key, sent as the x-paystack-signature header. Returns false (never
// throws) on any mismatch or malformed input.
export function verifyPaystackSignature(rawBody, signatureHeader, secretKey) {
  if (!signatureHeader || !secretKey) return false;
  const expected = nodeCrypto.createHmac('sha512', secretKey).update(rawBody).digest('hex');
  const a = Buffer.from(expected, 'utf8');
  const b = Buffer.from(signatureHeader, 'utf8');
  if (a.length !== b.length) return false;
  return nodeCrypto.timingSafeEqual(a, b);
}

async function paystackFetch(secretKey, path, init = {}) {
  const res = await fetch(`${PAYSTACK_API}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${secretKey}`,
      'Content-Type': 'application/json',
      ...init.headers,
    },
  });
  const body = await res.json().catch(() => null);
  if (!res.ok || !body?.status) {
    throw new Error(`Paystack ${path} failed: ${body?.message || res.statusText}`);
  }
  return body.data;
}

// Initialize Transaction → { authorization_url, access_code, reference }.
// amount is in subunits; reference is ours (makeReference()).
export function initializeTransaction(secretKey, { email, amount, currency, reference, callback_url, metadata }) {
  return paystackFetch(secretKey, '/transaction/initialize', {
    method: 'POST',
    body: JSON.stringify({ email, amount, currency, reference, callback_url, metadata }),
  });
}

// Verify Transaction → data with { status: 'success'|'failed'|'abandoned'|...,
// amount, currency, ... }. Used by the confirm page for immediate UX; the
// webhook remains the source of truth.
export function verifyTransaction(secretKey, reference) {
  return paystackFetch(secretKey, `/transaction/verify/${encodeURIComponent(reference)}`);
}
